# Generated by Django 4.2.4 on 2023-08-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('working', models.BooleanField(default=False)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
