# Generated by Django 4.2.4 on 2023-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('is_Active', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
